import "~/styles/globals.css";

import {GeistSans} from "geist/font/sans";
import {ClerkProvider} from "@clerk/nextjs";
import {TopNav} from "~/app/_components/topnav";
import {NextSSRPlugin} from "@uploadthing/react/next-ssr-plugin";
import {extractRouterConfig} from "uploadthing/server";
import {ourFileRouter} from "~/app/api/uploadthing/core";
import React from "react";
import {Toaster} from "~/components/ui/sonner";

export const metadata = {
    title: "T3 Gallery",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children, modal}: {
    children: React.ReactNode;
    modal: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en" className={`${GeistSans.variable}`}>
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
            <body className="dark">
                <div className="h-screen grid grid-rows-[auto,1fr]">
                    <TopNav/>
                    <main className="overflow-y-scroll">{children}</main>
                </div>
            {modal}
            <div id="modal-root"/>
            <Toaster richColors/>
            </body>
            </html>
        </ClerkProvider>
    );
}
